### ISSUE TITLE
ReadMe page

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Azure-security-privacy-and-compliance#4]
Please update ReadMe page with intro, target audience, and products & services.
Verify that WDS abstract is on the correct documents and HOL abstract is on the lab abstracts.

**Comment by DawnmarieDesJardins** [comment]
Removed Michael, added Kyle to this one.  Kyle, I'm not seeing Chris Givens in GitHub.  Can you help?  Thanks!

**Comment by kylebunting** [comment]
I've added @givenscj to the repo as a contributor, so once he accepts I'll assign all of these to him.

**Comment by givenscj** [comment]
Made updates to this page to add the requested information.

**Comment by DawnmarieDesJardins** [comment]
You are awesome, thank you!!!! 
Closing all issues.
