### ISSUE TITLE
Update path to Install_IIS.zip script in ARM template

### ISSUE THREAD

**Issue by joelhulen** [Microsoft/MCW-Azure-security-privacy-and-compliance#5]
Line 741 of the ARM template has a path to the `Install_IIS.zip` file that is the following: https://github.com/givenscj/mcw-azure-security/blob/master/Scripts/Install_IIS.zip?raw=true

Please update to: https://github.com/MCW-Azure-security-privacy-and-compliance/blob/master/Hands-on%20lab/Scripts/Install_IIS.zip?raw=true

This needs to be done **after** the testfix branch is merged to master.

**Comment by joelhulen** [comment]
Line 706 of the ARM template located within the **AzureTemplate** folder also has this path that needs to be updated.

**Comment by givenscj** [comment]
Updated!
