### ISSUE TITLE
Bad Link

### ISSUE THREAD

**Issue by nikki-conley** [Microsoft/MCW-Azure-security-privacy-and-compliance#7]
In the pre-lab work, the link for the deploy files is the Repo's root page.  Link needs to be updated.

Open a browser window to the cloud workshop GitHub repository (https://github.com/Microsoft/MCW-Azure-Security-Privacy-and-Compliance)

**Comment by DawnmarieDesJardins** [comment]
Hi Chris,
Can you please make sure this link is correct in the August test/fix?
Thanks! Dawnmarie

**Comment by givenscj** [comment]
This is the correct link.  They must download the repo with the solution files in the Hands On Lab folder.

**Comment by nikki-conley** [comment]
Maybe more specific of where that is since the link takes you back to the parent page?
